# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
reviews:
  # Enable auto-review for all PRs
  auto_review:
    enabled: true
    # Review PRs targeting any branch, not just default
    base_branches:
      - '.*'
  # Show review status in PR
  review_status: true
  # Request changes when issues are found
  request_changes_workflow: true
