import { ArrowLeft, MapPin, Clock, Camera } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const exampleTrips = [
  {
    title: 'Lofoten Islands',
    location: 'Norway',
    image: 'https://aiscout.photo/city-images/lofoten.jpg',
    spots: 10,
    highlights: [
      'Reine fishing village reflections',
      'Northern Lights at Haukland Beach',
      'Midnight sun at Reinebringen',
    ],
  },
  {
    title: 'Tokyo',
    location: 'Japan',
    image: 'https://aiscout.photo/city-images/tokyo.jpg',
    spots: 12,
    highlights: [
      'Shibuya Crossing at blue hour',
      'Senso-ji Temple at sunrise',
      'Tokyo Tower night views',
    ],
  },
  {
    title: 'Dolomites',
    location: 'Italy',
    image: 'https://aiscout.photo/city-images/dolomites.jpg',
    spots: 9,
    highlights: [
      'Tre Cime sunrise panorama',
      'Lago di Braies reflections',
      'Seceda ridgeline at golden hour',
    ],
  },
  {
    title: 'Iceland Ring Road',
    location: 'Iceland',
    image: 'https://aiscout.photo/city-images/iceland.jpg',
    spots: 15,
    highlights: [
      'Kirkjufell mountain compositions',
      'Jökulsárlón ice beach',
      'Seljalandsfoss waterfall behind',
    ],
  },
  {
    title: 'Patagonia',
    location: 'Argentina & Chile',
    image: 'https://aiscout.photo/city-images/patagonia.jpg',
    spots: 11,
    highlights: ['Torres del Paine sunrise', 'Fitz Roy alpenglow', 'Perito Moreno glacier calving'],
  },
  {
    title: 'Kyoto',
    location: 'Japan',
    image: 'https://aiscout.photo/city-images/kyoto.jpg',
    spots: 14,
    highlights: [
      'Fushimi Inari gates at dawn',
      'Arashiyama bamboo forest',
      'Kinkaku-ji golden reflections',
    ],
  },
];

/**
 * Render the Examples page that showcases predefined photo trip cards and provides navigation controls.
 *
 * @returns A JSX element for the Examples page containing the header, example trip cards, call-to-action, and footer.
 */
export function ExamplesPage() {
  const navigate = useNavigate();

  return (
    <div className="h-full overflow-y-auto bg-background">
      {/* Header */}
      <header className="flex items-center gap-3 px-4 py-3 border-b border-border bg-surface">
        <button onClick={() => navigate(-1)} className="p-2 -ml-2 press">
          <ArrowLeft className="w-5 h-5 text-foreground" />
        </button>
        <img src="/appicon.png" alt="PhotoScout" className="w-8 h-8 rounded-lg" />
        <h1 className="text-lg font-semibold text-foreground">Examples</h1>
      </header>

      <div className="p-4 space-y-6">
        {/* Intro */}
        <div className="text-center py-2">
          <h2 className="text-xl font-bold text-foreground mb-2">What You Can Create</h2>
          <p className="text-muted text-sm">
            Here are some example photo trips generated by PhotoScout. Each includes optimal times,
            locations, and interactive maps.
          </p>
        </div>

        {/* Example Trip Cards */}
        <div className="space-y-4">
          {exampleTrips.map((trip) => (
            <div
              key={trip.title}
              className="bg-card border border-border rounded-xl overflow-hidden"
            >
              {/* Destination Image */}
              <div className="relative h-36">
                <img src={trip.image} alt={trip.title} className="w-full h-full object-cover" />
                <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
                <div className="absolute bottom-3 left-3">
                  <h3 className="text-lg font-bold text-white">{trip.title}</h3>
                  <div className="flex items-center gap-1 text-white/80 text-xs">
                    <MapPin className="w-3 h-3" />
                    {trip.location}
                  </div>
                </div>
                <div className="absolute bottom-3 right-3 flex items-center gap-1 bg-black/40 backdrop-blur-sm px-2 py-1 rounded-full">
                  <Camera className="w-3 h-3 text-white" />
                  <span className="text-xs text-white">{trip.spots} spots</span>
                </div>
              </div>

              {/* Highlights */}
              <div className="p-3">
                <p className="text-xs text-muted mb-2 flex items-center gap-1">
                  <Clock className="w-3 h-3" />
                  Trip highlights
                </p>
                <ul className="space-y-1">
                  {trip.highlights.map((highlight, index) => (
                    <li key={index} className="text-sm text-foreground flex items-start gap-2">
                      <span className="text-primary mt-1">•</span>
                      {highlight}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          ))}
        </div>

        {/* CTA */}
        <div className="bg-card border border-border rounded-xl p-4 text-center">
          <p className="text-foreground text-sm mb-3">Ready to plan your own photo trip?</p>
          <button
            onClick={() => navigate('/login')}
            className="w-full py-3 px-4 bg-primary text-white rounded-lg font-medium text-sm"
          >
            Get Started
          </button>
        </div>

        {/* Footer */}
        <div className="text-center py-4">
          <p className="text-muted text-xs">© 2026 PhotoScout. All rights reserved.</p>
        </div>
      </div>
    </div>
  );
}